server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

logging:
  level:
    root: debug

customProperties:
#  quartzExpression: xxxx
#  ui-project-path: E:\WorkSpace\Idea\nimble\ui-helper\automation\
